"""Constants for the Trading 212 integration."""

from __future__ import annotations

from typing import Any

from homeassistant.const import Platform

DOMAIN = "trading212"
STORAGE_VERSION = 1
STORAGE_KEY_PREFIX = "trading212_daily_baseline"

PLATFORMS: list[Platform] = [Platform.SENSOR]

CONF_ACCOUNT_LABEL = "account_label"
CONF_API_KEY = "api_key"
CONF_API_SECRET = "api_secret"
CONF_ENVIRONMENT = "environment"
CONF_MAX_POSITION_ENTITIES = "max_position_entities"
CONF_POSITION_DISPLAY_FORMAT = "position_display_format"
CONF_UPDATE_INTERVAL = "update_interval"

FEATURE_ACCOUNT_SUMMARY = "account_summary"
FEATURE_POSITIONS_SUMMARY = "positions_summary"
FEATURE_PER_POSITION_ENTITIES = "per_position_entities"
FEATURE_PIES_SUMMARY = "pies_summary"
FEATURE_PER_PIE_ENTITIES = "per_pie_entities"
FEATURE_DIVIDENDS_SUMMARY = "dividends_summary"
FEATURE_ORDERS_SUMMARY = "orders_summary"
FEATURE_MOVERS_DAILY = "movers_daily"

FEATURE_OPTIONS: tuple[str, ...] = (
    FEATURE_ACCOUNT_SUMMARY,
    FEATURE_POSITIONS_SUMMARY,
    FEATURE_PER_POSITION_ENTITIES,
    FEATURE_PIES_SUMMARY,
    FEATURE_PER_PIE_ENTITIES,
    FEATURE_DIVIDENDS_SUMMARY,
    FEATURE_ORDERS_SUMMARY,
    FEATURE_MOVERS_DAILY,
)

DEFAULT_FEATURE_OPTIONS: dict[str, bool] = {
    FEATURE_ACCOUNT_SUMMARY: True,
    FEATURE_POSITIONS_SUMMARY: True,
    FEATURE_PER_POSITION_ENTITIES: False,
    FEATURE_PIES_SUMMARY: False,
    FEATURE_PER_PIE_ENTITIES: False,
    FEATURE_DIVIDENDS_SUMMARY: False,
    FEATURE_ORDERS_SUMMARY: False,
    FEATURE_MOVERS_DAILY: True,
}

ENDPOINT_GROUP_ACCOUNT_SUMMARY = "account_summary"
ENDPOINT_GROUP_POSITIONS = "positions"
ENDPOINT_GROUP_PIES = "pies"
ENDPOINT_GROUP_DIVIDENDS = "dividends"
ENDPOINT_GROUP_ORDERS = "orders"

IMPLEMENTED_ENDPOINT_GROUPS: set[str] = {
    ENDPOINT_GROUP_ACCOUNT_SUMMARY,
    ENDPOINT_GROUP_POSITIONS,
    ENDPOINT_GROUP_PIES,
}

ENDPOINT_GROUP_MIN_REFRESH_SECONDS: dict[str, int] = {
    ENDPOINT_GROUP_ACCOUNT_SUMMARY: 60,
    ENDPOINT_GROUP_POSITIONS: 60,
    ENDPOINT_GROUP_PIES: 30,
    ENDPOINT_GROUP_DIVIDENDS: 300,
    ENDPOINT_GROUP_ORDERS: 300,
}

DEFAULT_ACCOUNT_LABEL = "Trading 212"
DEFAULT_ENVIRONMENT = "live"
DEFAULT_MAX_POSITION_ENTITIES = 50
DEFAULT_POSITION_DISPLAY_FORMAT = "name"
DEFAULT_UPDATE_INTERVAL = 300

FEATURE_OPTION_DEFAULTS: dict[str, Any] = {
    **DEFAULT_FEATURE_OPTIONS,
    CONF_MAX_POSITION_ENTITIES: DEFAULT_MAX_POSITION_ENTITIES,
    CONF_POSITION_DISPLAY_FORMAT: DEFAULT_POSITION_DISPLAY_FORMAT,
}

POSITION_DISPLAY_FORMAT_NAME = "name"
POSITION_DISPLAY_FORMAT_TICKER = "ticker"
POSITION_DISPLAY_FORMAT_NAME_TICKER = "name_ticker"
POSITION_DISPLAY_FORMATS: tuple[str, ...] = (
    POSITION_DISPLAY_FORMAT_NAME,
    POSITION_DISPLAY_FORMAT_TICKER,
    POSITION_DISPLAY_FORMAT_NAME_TICKER,
)

MIN_POSITION_ENTITIES = 1
MIN_UPDATE_INTERVAL = 60
MAX_POSITION_ENTITIES = 250

ENVIRONMENT_URLS = {
    "live": "https://live.trading212.com/api/v0",
    "demo": "https://demo.trading212.com/api/v0",
}
